services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate && gunicorn --bind ${APP_HOST}:${APP_PORT} config.wsgi:application --workers 3"

  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - .env
    expose:
      - ${DB_PORT}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: