services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-config-dev.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:3000"

  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - docker-config-dev.env
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: