services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-config-dev.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:3000

  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - docker-config-dev.env
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: