# Generated by Django 5.1.2 on 2024-10-31 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='app.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=36, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
