# Generated by Django 5.1.2 on 2024-11-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transaction_wallet_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['id']},
        ),
    ]
